[project]
name = "fast-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bson>=0.5.10",
    "fastapi[standard]>=0.121.0",
    "motor>=3.7.1",
    "pydantic>=2.12.4",
]
